---
- name: LAB6 Nginx vhosts
  hosts: nginx
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: false

  vars:
    sites:
      - "fizfak.com"
      - "mehmat.com"
      - "biofak.com"

  roles:
    - role: lab6_ansible_vhosts
